sudo: required
env:
  global:
    - VERSION="1.0.2"
    - VERSION_WITH_BUILD="$VERSION.$TRAVIS_BUILD_NUMBER"
    - SOLUTION="src/Testing.Utilities.sln"

matrix:
  include:
    - if: (branch = master) AND NOT (repo =~ /\.private$/)
      env:
        - PRE_RELEASE="" VERSION_WITH_SUFFIX="$VERSION"
    - if: (branch != master) OR (repo =~ /\.private$/)
      env:
        - PRE_RELEASE="-ci.$TRAVIS_BUILD_NUMBER" VERSION_WITH_SUFFIX="$VERSION$PRE_RELEASE"

language: csharp
mono: none
dotnet: 3.0

script:
  - dotnet restore "$SOLUTION"
  - dotnet build "$SOLUTION" -c Release -p:VersionPrefix="$VERSION" -p:VersionSuffix="$PRE_RELEASE" -p:AssemblyVersion="$VERSION_WITH_BUILD" -p:FileVersion="$VERSION_WITH_BUILD" -p:InformationalVersion="$VERSION_WITH_SUFFIX"
  - dotnet pack "$SOLUTION" -c Release --include-symbols --no-build -p:SymbolPackageFormat=snupkg -p:Version="$VERSION_WITH_SUFFIX"

deploy:
  on:
    all_branches: true
  skip_cleanup: true
  provider: script
  script:
    - dotnet nuget push "src/Testing.Utilities/bin/Release/Lophtware.Testing.Utilities.$VERSION_WITH_SUFFIX.nupkg" -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
